#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook...${no_color}\n"

FILES_PATTERN='\.(jsx?|tsx?)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info|warn|error]'

echo -e "${green}No console. or debugger references found!${no_color}\n"
echo -e "${green}Git pre-commit hook was successful!${no_color}\n"

#execute lint-staged script
exec >/dev/tty 2>&1

npx lint-staged

